services:
  - type: web
    name: fb-webhook-proxy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
    envVars:
      - key: FORWARD_URL
        value: https://n8n.ai-assistant-integration.realiste.dev/webhook/fbapp
